In [1]:
import numpy as np



In [45]:
a = np.array([1,2,3])
print(type(a))

print(a.shape)
a = np.eye(2)
a = np.zeros((3,3))
b = np.ones((2,2))
c = np.full((3,3),100)
c
d = np.eye(3)
d
e = np.random.random((3,3))
c
f = c[1:3, 1:3]
f[0][0] = 50
c.shape

<class 'numpy.ndarray'>
(3,)


(3, 3)

In [55]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(a)
b = np.array([0,2,0,1])
print(b)

print(a[np.arange(4),b])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>3])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 3  4  5  6  7  8  9 10 11 12]
[ 4  5  6  7  8  9 10 11 12]


In [58]:
x = np.array([[[1,2],[3,4]],[6,8]])
print(x)

[[list([1, 2]) list([3, 4])]
 [6 8]]
