In [5]:
import numpy as np

In [6]:
a = np.eye(2) # [[1., 0.],[0., 1.]]
type(a[0,0])

numpy.float64

In [7]:
b = np.random.random((3,5,3))

In [8]:
b

array([[[0.81214   , 0.74255092, 0.45555196],
        [0.07891035, 0.17320169, 0.41537644],
        [0.17833275, 0.06456335, 0.5066794 ],
        [0.27357037, 0.79159125, 0.73858332],
        [0.90476602, 0.15620095, 0.75077278]],

       [[0.20964765, 0.60782347, 0.31816587],
        [0.56296251, 0.67662066, 0.6663994 ],
        [0.4803136 , 0.35830996, 0.03823825],
        [0.00347183, 0.64384327, 0.02414131],
        [0.69804405, 0.7149595 , 0.0721153 ]],

       [[0.2265288 , 0.80455381, 0.87215306],
        [0.3417546 , 0.45769346, 0.88187806],
        [0.97085829, 0.1639631 , 0.13794374],
        [0.12691611, 0.32327508, 0.94078091],
        [0.67808585, 0.54630687, 0.75915453]]])

In [9]:
b[1, 3, 2]

0.024141308106395476

In [10]:
b[1]

array([[0.20964765, 0.60782347, 0.31816587],
       [0.56296251, 0.67662066, 0.6663994 ],
       [0.4803136 , 0.35830996, 0.03823825],
       [0.00347183, 0.64384327, 0.02414131],
       [0.69804405, 0.7149595 , 0.0721153 ]])

In [11]:
b[1, 3].shape

(3,)

In [12]:
a = np.random.random((3,4))

In [13]:
a

array([[0.44658507, 0.05122823, 0.55229485, 0.18993817],
       [0.55395612, 0.57354935, 0.94414461, 0.23263646],
       [0.47780126, 0.95407924, 0.62154097, 0.37282812]])

In [14]:
b = a[1:, 2]
b

array([0.94414461, 0.62154097])

In [15]:
b[0] = 2

In [16]:
b

array([2.        , 0.62154097])

In [47]:
a

array([[0.44658507, 0.05122823, 0.55229485, 0.18993817],
       [0.55395612, 0.57354935, 2.        , 0.23263646],
       [0.47780126, 0.95407924, 0.62154097, 0.37282812]])

In [48]:
a[[1, 2, 2], [0, 1 ,1 ]]

array([0.55395612, 0.95407924, 0.95407924])

In [49]:
c = a[[1,2,2], [0,1, 1]]

In [50]:
c

array([0.55395612, 0.95407924, 0.95407924])

In [51]:
c[2] = 8

In [52]:
a

array([[0.44658507, 0.05122823, 0.55229485, 0.18993817],
       [0.55395612, 0.57354935, 2.        , 0.23263646],
       [0.47780126, 0.95407924, 0.62154097, 0.37282812]])

In [59]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [80]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [81]:
# df.iloc[[0],:4]
# df.loc[0]
# df['index1'] = np.arange(150)+1

In [82]:
# df= df.set_index('index1')
# # df.set_index('sepal length (cm)')
# # df = df.reset_index()
# df.loc[2]

In [83]:
# # df.rename(columns = {'sepal length (cm)' : 'sl', 'sepal width (cm)' : 'sw',
# #                     'petal length (cm)' : 'pl', 'petal width (cm)' : 'pw' }, inplace = True)

# df['sl'] = df['sl'].apply(lambda x : x*2)
# # df['sl'].value_counts()
# df

In [84]:
df2 = pd.DataFrame(iris.data, columns=iris.feature_names)
df2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [89]:
df.rename(columns = {'sepal length (cm)' : 'sl', 'sepal width (cm)' : 'sw',
                    'petal length (cm)' : 'pl', 'petal width (cm)' : 'pw' }, inplace = True)

df2.rename(columns = {'sepal length (cm)' : 'sl', 'sepal width (cm)' : 'sw2',
                    'petal length (cm)' : 'pl2', 'petal width (cm)' : 'pw2' }, inplace = True)


In [90]:
df.head()

sl   sw   pl   pw
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [99]:
df2.head()
df.loc[df['sl']>7, ['sl','pw']]

sl   pw
102  7.1  2.1
105  7.6  2.1
107  7.3  1.8
109  7.2  2.5
117  7.7  2.2
118  7.7  2.3
122  7.7  2.0
125  7.2  1.8
129  7.2  1.6
130  7.4  1.9
131  7.9  2.0
135  7.7  2.3

In [94]:
test= pd.concat([df,df2], axis= 1)
test

sl   sw   pl   pw   sl  sw2  pl2  pw2
0    5.1  3.5  1.4  0.2  5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2  4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2  4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2  4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2  5.0  3.6  1.4  0.2
5    5.4  3.9  1.7  0.4  5.4  3.9  1.7  0.4
6    4.6  3.4  1.4  0.3  4.6  3.4  1.4  0.3
7    5.0  3.4  1.5  0.2  5.0  3.4  1.5  0.2
8    4.4  2.9  1.4  0.2  4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1  4.9  3.1  1.5  0.1
10   5.4  3.7  1.5  0.2  5.4  3.7  1.5  0.2
11   4.8  3.4  1.6  0.2  4.8  3.4  1.6  0.2
12   4.8  3.0  1.4  0.1  4.8  3.0  1.4  0.1
13   4.3  3.0  1.1  0.1  4.3  3.0  1.1  0.1
14   5.8  4.0  1.2  0.2  5.8  4.0  1.2  0.2
15   5.7  4.4  1.5  0.4  5.7  4.4  1.5  0.4
16   5.4  3.9  1.3  0.4  5.4  3.9  1.3  0.4
17   5.1  3.5  1.4  0.3  5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3  5.7  3.8  1.7  0.3
19   5.1  3.8  1.5  0.3  5.1  3.8  1.5  0.3
20   5.4  3.4  1.7  0.2  5.4  3.4  1.7  0.2
21   5.1  3.7  1.5  0.4  5.1  3.7  1.5  0.4
22   4.6  3.6  1.0  0.2  4.6  3.6  1.0  0.2
23   5.1  3.3  1.7  0.5  5.1  3.3  1.7  0.5
24   4.8  3.4  1.9  0.2  4.8  3.4  1.9  0.2
25   5.0  3.0  1.6  0.2  5.0  3.0  1.6  0.2
26   5.0  3.4  1.6  0.4  5.0  3.4  1.6  0.4
27   5.2  3.5  1.5  0.2  5.2  3.5  1.5  0.2
28   5.2  3.4  1.4  0.2  5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2  4.7  3.2  1.6  0.2
..   ...  ...  ...  ...  ...  ...  ...  ...
120  6.9  3.2  5.7  2.3  6.9  3.2  5.7  2.3
121  5.6  2.8  4.9  2.0  5.6  2.8  4.9  2.0
122  7.7  2.8  6.7  2.0  7.7  2.8  6.7  2.0
123  6.3  2.7  4.9  1.8  6.3  2.7  4.9  1.8
124  6.7  3.3  5.7  2.1  6.7  3.3  5.7  2.1
125  7.2  3.2  6.0  1.8  7.2  3.2  6.0  1.8
126  6.2  2.8  4.8  1.8  6.2  2.8  4.8  1.8
127  6.1  3.0  4.9  1.8  6.1  3.0  4.9  1.8
128  6.4  2.8  5.6  2.1  6.4  2.8  5.6  2.1
129  7.2  3.0  5.8  1.6  7.2  3.0  5.8  1.6
130  7.4  2.8  6.1  1.9  7.4  2.8  6.1  1.9
131  7.9  3.8  6.4  2.0  7.9  3.8  6.4  2.0
132  6.4  2.8  5.6  2.2  6.4  2.8  5.6  2.2
133  6.3  2.8  5.1  1.5  6.3  2.8  5.1  1.5
134  6.1  2.6  5.6  1.4  6.1  2.6  5.6  1.4
135  7.7  3.0  6.1  2.3  7.7  3.0  6.1  2.3
136  6.3  3.4  5.6  2.4  6.3  3.4  5.6  2.4
137  6.4  3.1  5.5  1.8  6.4  3.1  5.5  1.8
138  6.0  3.0  4.8  1.8  6.0  3.0  4.8  1.8
139  6.9  3.1  5.4  2.1  6.9  3.1  5.4  2.1
140  6.7  3.1  5.6  2.4  6.7  3.1  5.6  2.4
141  6.9  3.1  5.1  2.3  6.9  3.1  5.1  2.3
142  5.8  2.7  5.1  1.9  5.8  2.7  5.1  1.9
143  6.8  3.2  5.9  2.3  6.8  3.2  5.9  2.3
144  6.7  3.3  5.7  2.5  6.7  3.3  5.7  2.5
145  6.7  3.0  5.2  2.3  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8  5.9  3.0  5.1  1.8

[150 rows x 8 columns]